---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: "db_table"
  rules:
    - actions: ["select"]
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.org_id == request.principal.attr.org_id
              - expr: request.resource.id in request.principal.attr.table_scope
              - expr: "'select' in request.principal.attr.capabilities"
      output:
        when:
          ruleActivated: '{"rowFilter": request.principal.attr.row_filter, "maskedColumns": request.principal.attr.masked_columns}'

    - actions: ["insert"]
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.org_id == request.principal.attr.org_id
              - expr: request.resource.id in request.principal.attr.table_scope
              - expr: "'insert' in request.principal.attr.capabilities"
      output:
        when:
          ruleActivated: '{"rowFilter": request.principal.attr.row_filter, "maskedColumns": request.principal.attr.masked_columns}'

    - actions: ["update"]
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.org_id == request.principal.attr.org_id
              - expr: request.resource.id in request.principal.attr.table_scope
              - expr: "'update' in request.principal.attr.capabilities"
      output:
        when:
          ruleActivated: '{"rowFilter": request.principal.attr.row_filter, "maskedColumns": request.principal.attr.masked_columns}'

    - actions: ["delete"]
      effect: EFFECT_ALLOW
      roles: ["*"]
      condition:
        match:
          all:
            of:
              - expr: request.resource.attr.org_id == request.principal.attr.org_id
              - expr: request.resource.id in request.principal.attr.table_scope
              - expr: "'delete' in request.principal.attr.capabilities"
      output:
        when:
          ruleActivated: '{"rowFilter": request.principal.attr.row_filter, "maskedColumns": request.principal.attr.masked_columns}'
